org: gabrielbarbosagv
app: scraper-generation
service: scraper-generation
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
